spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mb?useUnicode=yes&characterEncoding=UTF-8&useSSL=true&createDatabaseIfNotExist=true&publicKeyRetrieval=true&serverTimezone=UTC
    username: asdasdqwe
    password: S6^e68OC@asddada#h
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

